apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-flaskapp
  namespace: helm-argo
spec:
  destination:
    name: ''
    namespace: sow
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/GnanaSowndharya/flaskapp-helm.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
